### ISSUE TITLE
Soft real time initialization by batch file

### ISSUE THREAD

**Issue by vcarlucci** [MicrosoftDocs/windows-iot-public#11]
Hi,
According the [windows soft real time doc](https://learn.microsoft.com/en-us/windows/iot/iot-enterprise/soft-real-time/soft-real-time) we tried to make a batch file according the recommanded initialization each time the OS starts.

I tested under OS MS Windows 11 Enterprise Evaluation. Dev VM available from MS [here](https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/).
Note: Soft real time is documented under Windows 10 IoT Enterprise, but I think or hope that should work too under our used Win11.

1. From chapter **Device Configuration** I copied points 1 to 6 into a batch file (attached windowsIotSRT.bat.txt -> delete .txt from file because batch file is not supported here) and I added some notes around:

[windowsIotSRT.bat.txt](https://github.com/MicrosoftDocs/windows-iot-public/files/10127258/windowsIotSRT.bat.txt) Run this batch file as admin seems all doing fine! 👍

2. Again from chapter **Device Configuration** I tried to insert the description for **Use MDM Bridge WMI Provider to Configure the WindowsIoT CSP** into a batch file too, but this is not working. The described download/installation of psexec tools I have also somehow described directly in the batch as comment, which has to be done by manual installation if I understand that correctly.

[windowsIotSRT CSP.bat.txt](https://github.com/MicrosoftDocs/windows-iot-public/files/10127375/windowsIotSRT.CSP.bat.txt) **How we get that chapter "CSP" running by a batch?**

@rsameser @skuriki 
As contributors of the [windows soft real time doc](https://learn.microsoft.com/en-us/windows/iot/iot-enterprise/soft-real-time/soft-real-time), can you support here?

**Comment by hez2010** [comment]
I don't think Windows 11 has soft realtime implemented. The Windows 10 IoT Enterprise is a special edition that comes with the soft realtime feature.

**Comment by vcarlucci** [comment]
@hez2010 thank's for quick answer.
We tested it on Win 10 Enterprise, same there, the setup with CSP it is not working there. Meantime will organize Win 10 IoT Enterprise and try the same there. We are also not sure if our created second batch file is working or not, can you have a look to that if it is done correct? https://github.com/MicrosoftDocs/windows-iot-public/issues/11 with attached batch file "windowsIotSRT CSP.bat".

**Comment by vcarlucci** [comment]
Hello @hez2010 
Finally I could test this on a Win 10 IoT Enterprise 21H2 (LTSC). I had to modify the attached file on top "windowsIotSRT CSP.bat", tried it also manually and now seems changing somehow the 12 cores on our test machine. I defined 8 cores for RT on my configuration.

The issue is now, how I get all that validated that it works like expected? 

**Without validation we can not move on with that.**

- The windows task manager performance view of the cores now has switched to 100% for all 12 cores during the whole time, even if there is running nothing. I believe this is because the cpu idle is now disabled? I would expect that 8 cores could change, but that all show now differently is weired for me.. So no indication if all that is working as expected.
- If I make a small test application in C# with the suggested affinity (core index 4 to 11) with a process prio as realtime and run a small infinite while-loop, I can not even see which core is involved and which ones not because as described already, all is permanent in 100%.
- If I make another small test application in C# without any affinity or rt settings like above, we should see only core 0-3 involved, but as already written, all is permanent 100% and we can't validate this.


Great and powerfull feature publication, but somehow it fails in the details which is most important for use.

FYI
@rsameser @skuriki

**Comment by vcarlucci** [comment]
Can someone link this issue to the right place so I can get support here? That would be great. 
Thank's!

**Comment by Sars47** [comment]
Hi @vcarlucci your assumption that the 100% core utilization is happening because CPU idle states has been disabled is correct. Since this occurs system-wide, rather than only on the cores that have been designated as reserved for real-time, it sounds like your system is behaving as expected.

It sounds like you're trying to use CPU utilization as a way of verifying that Soft RT has been correctly enabled. I would instead recommend using an [ETL trace](https://learn.microsoft.com/en-us/windows/win32/etw/event-tracing-portal) to directly verify which workloads are running on which cores, because as you've noticed CPU utilization is not a useful measure when idle states are disabled.

**Comment by vcarlucci** [comment]
Hi @Sars47 thank you for the input.

It will take some extra effort to get that on our system. For our soft real-time use case, not only do we need to set up the system, but we also need to do deep verification that all the settings are working as expected, and the core's workload analysis is the critical part of that. Maybe in the future, developers will get an easier way to somehow get that information directly. Until then, we will continue as you mentioned with the ETL trace.

Thank's!

**Comment by tommasofurieri** [comment]
@vcarlucci can you please share the final CSP bat file? Did you manage to verify the correctness of application of the RT and core isolation settings?

**Comment by tommasofurieri** [comment]
@vcarlucci did you manage to check the deep verification that all the settings are working as expected that you mentioned?
Can you please share the "final" working "windowsIotSRT CSP.bat.txt"?

**Comment by frax2222** [comment]
[softrealtime.bat.txt](https://github.com/user-attachments/files/31238843/softrealtime.bat.txt)

Please find attached batch file performing Realtime Configuration from the Command Line (including CSP).

Adjust $obj.SetRTCores = 1 to correct number.

psexec.exe must be in same directory as this batch file.
