### ISSUE TITLE
Broken link in Licensing.md

### ISSUE THREAD

**Issue by ElizabethGreene** [MicrosoftDocs/windows-iot-public#5]
On this page: https://github.com/MicrosoftDocs/windows-iot-public/blob/805f88a57d59a56ab399a5d893a8bf43e5b23d35/windows-iot/iot-enterprise/Commercialization/Licensing.md

Under Licensing and Usage it says "You can retrieve a license by contacting a [Windows IoT Distributor](https://aka.ms/IoTDistributorList) or " ... The URL for the IoT Distributor list returns a 404 error.

**Comment by TerryWarwick** [comment]
@ElizabethGreene, thank you for reporting this issue.  The link has been fixed for quite some time.  I apologize for not closing the loop with you earlier.  Please review the content and close this open issue if your original issue has been resolved.

**Comment by ElizabethGreene** [comment]
It looks good now.  I'll close this.  Thanks!
